name: DotENV

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:

env:
  version: '3.0.${{ github.run_number }}'
  dotnetVersion: '8'
  repoUrl: ${{ github.server_url }}/${{ github.repository }}
  vsixPath: ${{ github.workspace }}/src/bin/Release/net8.0-windows8.0/DotENV.vsix

jobs:
  build:
    name: 🛠️ Build
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ env.dotnetVersion }}.x

      - name: Build VSIX
        run: dotnet publish -p:Version=${{ env.version }}

      - name: Publish Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: DotENV
          path: |
            ${{ env.vsixPath }}
            publish-manifest.json
            README.md

  release:
    if: github.ref_name == 'main'
    name: 🚀 Release
    needs: build
    runs-on: windows-latest
    environment: Release
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v5
        with:
          merge-multiple: true

      - name: Tag release
        id: tag_release
        uses: mathieudutour/github-tag-action@v6.2
        with:
          custom_tag: '${{ env.version }}'
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_release.outputs.new_tag }}
          name: ${{ steps.tag_release.outputs.new_tag }}
          body: ${{ steps.tag_release.outputs.changelog }}
          artifacts: ${{ env.vsixPath }}
          skipIfReleaseExists: true
          
      - name: Publish to Marketplace
        uses: cezarypiatek/VsixPublisherAction@1.1
        with:
          extension-file: ${{ env.vsixPath }}
          publish-manifest-file: publish-manifest.json
          personal-access-code: ${{ secrets.VS_PUBLISHER_ACCESS_TOKEN }}

      - name: Publish to Open VSIX Gallery
        run: |
           curl -L 'https://www.vsixgallery.com/api/upload?repo=${{ env.repoUrl }}&issuetracker=${{ env.repoUrl }}/issues' -F 'file=@"${{ env.vsixPath }}"'